//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMLWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronogramaDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CronogramaDetalle()
        {
            this.PlanMantenimientoDetalle = new HashSet<PlanMantenimientoDetalle>();
        }
    
        public int codigo { get; set; }
        public int codigo_cronograma { get; set; }
        public int semana { get; set; }
        public string actividad { get; set; }
        public string asignada { get; set; }
    
        public virtual Cronograma Cronograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanMantenimientoDetalle> PlanMantenimientoDetalle { get; set; }
    }
}
