//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMLWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public int codigo { get; set; }
        public int codigo_plan { get; set; }
        public int codigo_tecnico { get; set; }
    
        public virtual PlanMantenimiento PlanMantenimiento { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
