//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMLWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenServicio
    {
        public int codigo { get; set; }
        public string numero { get; set; }
        public string observacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public int codigo_equipo { get; set; }
        public int codigo_tecnico { get; set; }
        public Nullable<int> codigo_solicitud { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Solicitud Solicitud { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
